### ISSUE TITLE
Key of Khaj Nisut stacks not working correctly

### ISSUE THREAD

**Issue by AleXu224** [TeucerDev/little-bro#3]
Gives the same ammount of EM at 1 stack, 2 stacks and 3 stacks
![image](https://user-images.githubusercontent.com/20338170/194170268-2e231f19-1707-4706-ab5f-5a7c3b056ff2.png)
![image](https://user-images.githubusercontent.com/20338170/194170290-3fe1447d-2e0e-468c-af87-d5bc8264b96b.png)
![image](https://user-images.githubusercontent.com/20338170/194170319-dcb15f38-199f-408f-9f62-5b0f98d7518d.png)

**Comment by TeucerDev** [comment]
Fixed in 8.23.4-t7
