### ISSUE TITLE
Dehya C1 should be adjusted to match CN text values

### ISSUE THREAD

**Issue by kbphan** [TeucerDev/little-bro#7]
Please note that the text below has been google translated, just use the values instead of the text.

Dixia's maximum health is increased by 15%; In addition, based on the maximum health, the damage caused by the following attacks of Dixia increases:
· Molten Iron Stream Damage Increase: 5.2% of maximum health;
· Roaring Lion Bite Damage Increase: 8.4% of the maximum health.

**Comment by TeucerDev** [comment]
Fixed with new datamine
